### PR TITLE
Html

### PR DESCRIPTION
**Pull request by maegek**

### CODE REVIEW

**Comment by maegek** [comment]
Added output files, too

**Comment by fbessez** [comment]
Hey @maegek, looks great. Do you mind writing up a quick guide on how to use your changes and add it to the README?

**Comment by maegek** [comment]
Oh, oops, I didn't mean to make this pull request here, just on my fork. This would need some work before it becomes anything that someone else would want to use (currently, it just swipes all people right and all ads left)

**Comment by fbessez** [comment]
@maegek ok cool, yea it seemed like that's what was going on so I thought maybe I was misunderstanding it.

**Pull request closed without merging**
